name: dsbuntis
description: Crawl the DSB/DSBMobile API and parse Untis's HTML.
version: 8.1.0-alpha.4
homepage: https://github.com/Ampless/dsbuntis

environment:
  sdk: ^3.0.0

dependencies:
  dsb: ^0.1.2-alpha.0
  schttp: ^5.0.0
  untis: ^0.2.0-alpha.5
  where_not_null: ^1.0.0

dev_dependencies:
  lints: ^5.0.0
  # for `expect` in `assertPlanListsEqual`
  test: ^1.25.0
  tested: ^1.0.0
