name: dsbuntis
description: This package allows you to crawl the DSB/DSBMobile API and parse Untis's HTML.
version: 8.1.0-alpha.3
homepage: https://github.com/Ampless/dsbuntis

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  dsb: ^0.1.1-alpha.3
  schttp: ^5.0.0-alpha.9
  untis: ^0.2.0-alpha.3
  where_not_null: ^1.0.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.1
  tested: ^1.0.0-alpha.2
