name: dsbuntis
description: This package allows you to crawl the DSB/DSBMobile API and parse Untis's HTML.
version: 8.1.0-alpha.2
homepage: https://github.com/Ampless/dsbuntis

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  dsb: ^0.1.1-alpha.1
  schttp: ^5.0.0-alpha.2
  untis: ^0.2.0-alpha.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.1
