name: untis
description: This package allows you to parse Untis's HTML.
version: 0.2.0-alpha.5
homepage: https://github.com/Ampless/dsbuntis

environment:
  sdk: ^3.0.0

dependencies:
  html: ^0.15.5
  html_unescape: ^2.0.0
  html_search: ^0.3.0
  where_not_null: ^1.0.0

dev_dependencies:
  lints: ^5.0.0
  # for `sortTestCase` and `assertPageListsEqual`
  test: ^1.25.0
  tested: ^1.0.0
