name: dsbuntis
description: A library for using DSB's API and parsing Untis plans.
version: 0.1.0
homepage: https://github.com/Ampless/dsbuntis

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  html: ^0.14.0+3
  archive: ^2.0.13
  uuid: ^2.2.2

dev_dependencies:
  test: any

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
