name: dsbuntis
description: This package allows you to crawl DSB's "Mobile API" and parse Untis's HTML.
version: 6.0.0-alpha.2
homepage: https://github.com/Ampless/dsbuntis

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  html: ^0.15.0
  html_unescape: ^2.0.0
  html_search: ^0.2.0
  schttp: ^3.2.0

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.17.10
  test_coverage_badge: ^0.2.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
