name: dsbuntis
description: This package allows you to crawl the DSB/DSBMobile API and parse Untis's HTML.
version: 7.0.0-alpha.3
homepage: https://github.com/Ampless/dsbuntis

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  html: ^0.15.0
  html_unescape: ^2.0.0
  html_search: ^0.2.0
  schttp: ^4.0.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.18.2
  test_coverage_badge: ^0.2.0
