name: dsbuntis
description: This package allows you to crawl DSB's "Mobile API" and parse Untis's HTML.
version: 3.2.0
homepage: https://github.com/Ampless/dsbuntis

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  html: ^0.15.0
  html_unescape: ^2.0.0-nullsafety.0
  html_search: ^0.1.1
  schttp: ^2.0.0

dev_dependencies:
  test: ^1.16.7
  pedantic: ^1.11.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
