name: dsbuntis
description: This package allows you to crawl DSB's "Android API" and parse Untis's HTML.
version: 0.1.9
homepage: https://github.com/Ampless/dsbuntis

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  html: ^0.14.0+3
  archive: ^2.0.13
  uuid: ^2.2.2

dev_dependencies:
  test: any
  pedantic: any

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
