name: dsbuntis
description: This package allows you to crawl DSB's "Android API" and parse Untis's HTML.
version: 2.0.0-nullsafety.0
homepage: https://github.com/Ampless/dsbuntis

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  html: ^0.14.0+4
  archive: ^3.0.0-nullsafety.0
  uuid: ^3.0.0-nullsafety.0
  html_unescape: ^2.0.0-nullsafety.0
  html_search: ^0.1.0-nullsafety.0
  schttp: ^1.0.0-nullsafety.0

dev_dependencies:
  test: ^1.16.0-nullsafety.16
  pedantic: ^1.10.0-nullsafety.3
  test_coverage: any

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
