name: accemus
description: A CLI tool for fetching substitution plans from DSB/DSBMobile and
  parsing Untis HTML, as well as debugging dsbuntis.
version: 0.2.1-alpha.1
homepage: https://github.com/Ampless/dsbuntis

environment:
  sdk: ^3.0.0

executables:
  accemus: accemus

dependencies:
  ansicolor: ^2.0.1
  args: ^2.5.0
  dsb: ^0.1.2-alpha.0
  dsbuntis: ^8.1.0-alpha.4
  hex: ^0.2.0
  highlight: ^0.7.0
  schttp: ^5.0.0

dev_dependencies:
  lints: ^5.0.0
  tested: ^1.0.0
