name: dsb
description: This package allows you to crawl the DSB/DSBMobile API.
version: 0.1.0-alpha.2
homepage: https://github.com/Ampless/dsbuntis

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  schttp: ^4.1.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.1
