name: dsb
description: This package allows you to interact with the DSB/DSBMobile API.
version: 0.1.1-alpha.3
homepage: https://github.com/Ampless/dsbuntis

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  schttp: ^5.0.0-alpha.9

dev_dependencies:
  lints: ^2.0.1
  tested: ^1.0.0-alpha.2
