name: dsb
description: This package allows you to crawl the DSB/DSBMobile API.
version: 0.1.1-alpha.0
homepage: https://github.com/Ampless/dsbuntis

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  schttp: ^5.0.0-alpha.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.1
