name: dsb
description: This package allows you to interact with the DSB/DSBMobile API.
version: 0.1.1
homepage: https://github.com/Ampless/dsbuntis

environment:
  sdk: ^3.0.0

dependencies:
  schttp: ^5.0.0

dev_dependencies:
  lints: ^2.1.0
  tested: ^1.0.0
