name: Test

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        package: [dsb, untis, dsbuntis, accemus]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: beta
      - run: cd packages/${{ matrix.package }} && dart test --file-reporter=json:results.json
      - uses: dorny/test-reporter@v3
        if: success() || failure()
        with:
          name: ${{ matrix.package }} Tests
          path: packages/${{ matrix.package }}/results.json
          reporter: dart-json
